In [1]:
from numpy import exp, array, random, dot, mean, abs

In [4]:
import numpy

In [5]:
veriler= array ([[1,1,0,1,1,1],[1,1,0,0,1,1],[1,1,0,0,1,0],[1,1,1,1,1,1],[1,1,1,0,0,1],[0,0,0,0,0,0],[0,1,1,0,1,1],[0,0,0,1,1,1],[0,0,1,0,0,1],[0,0,1,0,1,0]])

In [6]:
print((veriler))

[[1 1 0 1 1 1]
 [1 1 0 0 1 1]
 [1 1 0 0 1 0]
 [1 1 1 1 1 1]
 [1 1 1 0 0 1]
 [0 0 0 0 0 0]
 [0 1 1 0 1 1]
 [0 0 0 1 1 1]
 [0 0 1 0 0 1]
 [0 0 1 0 1 0]]


In [7]:
testsonuc= array ([[0.9,0.6,0.5,1,0.4,0,0.7,0.7,0.2,0.4]])

In [8]:
print((testsonuc))

[[0.9 0.6 0.5 1.  0.4 0.  0.7 0.7 0.2 0.4]]


In [9]:
testsonuc=testsonuc.T

In [10]:
agirlik = array([[1.0,1.0,1.0,1.0,1.0,1.0]])

In [11]:
print((agirlik))

[[1. 1. 1. 1. 1. 1.]]


In [12]:
agirlik = agirlik.T

In [13]:
for ogrenim in range(1000):
    hücredegeri = dot(veriler,agirlik)
    tahmin = 1 / (1+ exp(-hücredegeri))
    #print((tahmin))
    #print(( ))
    agirlik = agirlik + dot(veriler.T,((testsonuc-tahmin)* tahmin* (1-tahmin)))
    #print((agirlik))
    print((str(numpy.mean(numpy.abs(testsonuc-tahmin)))))

0.37085635519467064
0.36134297586903413
0.3474084151911164
0.32617682090543065
0.2928332377768358
0.24106605459139954
0.18791191737256935
0.16897026926748698
0.16426887317603794
0.16271412742743796
0.16101797787776592
0.15943522585064812
0.15792489641308113
0.15648145544293432
0.1550974756791386
0.15376721247046868
0.15248587592265522
0.1512494484513069
0.1500545126074719
0.1488981263850674
0.14777772910163695
0.14669106993568287
0.14563615302399302
0.14461119478538684
0.14361459035076812
0.1426448868432678
0.14170076186496938
0.14078100598323678
0.1398845083224339
0.1390102445924726
0.13815726704964232
0.1373246960053352
0.13651171258703215
0.13571888161905682
0.13521877574418883
0.13473106799294593
0.1342553957666477
0.13379140299330955
0.1333387406780007
0.1328970673683607
0.1324660495370832
0.13204536188535068
0.1316346875726187
0.13123371837897396
0.130842154806679
0.13045970612758032
0.13008609038290203
0.12972103434162974
0.12936427342328702
0.12901555159044098
0.128674621215789

In [14]:
yeniveri= array ([[1,1,1,1,1,1]])

In [15]:
yenitahmin = 1 / (1+exp(-(dot(yeniveri,agirlik))))

In [16]:
print((yenitahmin))

[[0.85835156]]
